"""add ticket status

Revision ID: c51e8ec6208a
Revises: 7de5ad0886d2
Create Date: 2026-09-17 14:55:05.637082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51e8ec6208a'
down_revision: Union[str, Sequence[str], None] = '7de5ad0886d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.Enum('active', 'canceled', name='ticketstatus', native_enum=False), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'status')
    # ### end Alembic commands ###
